@baseURL = http://localhost:3000
###
GET {{ baseURL }}/smarttag
###
GET  {{ baseURL }}/smarttag/6575d52a18c3a60c6dda385c HTTP/1.1

###
POST  {{ baseURL }}/smarttag HTTP/1.1
content-type: application/json

{
    "tagId":"6574bc0a33b0131a514f7085",
    "agencyId":"656f4472a461bb97c821168a",
    "creatorId":"656f4761d765ee2dda21078c",
    "minimumAmount":5,
    "maximumAmount":10
}

###
PUT {{ baseURL }}/smarttag/6575d5a44b0f79b2c18557bf HTTP/1.1
content-type: application/json

{
    "minimumAmount":15,
    "maximumAmount":20
}

###
DELETE {{ baseURL }}/smarttag/6575d52a18c3a60c6dda385c HTTP/1.1